services:
  api:
    build:
      dockerfile: Dockerfile
      target: dev
      context: .
    volumes:
      - ./:/workspace/
      - node_modules:/workspace/app/node_modules
    command: npm run start:docker
    environment:
      - DATABASE_URL=postgresql://postgres:asdfasdf@db:5432/postgres?schema=public

  apiunit:
    build:
      dockerfile: Dockerfile
      target: dev
      context: .
    volumes:
      - ./:/workspace/
      - node_modules:/workspace/app/node_modules
    command: npm run test:watch:docker

  apie2e:
    build:
      dockerfile: Dockerfile
      target: dev
      context: .
    volumes:
      - ./:/workspace/
      - ./.git:/workspace/.git
      - node_modules:/workspace/app/node_modules
    command: npm run test:e2e:docker
    environment:
      - DATABASE_URL=postgresql://postgres:asdfasdf@db:5432/test?schema=public

  db:
    image: library/postgres:13.1-alpine
    ports:
    - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data
  proxy:
    image: jwilder/nginx-proxy:alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

volumes:
  db:
  node_modules:
