services:
  api:
    image: docker.pkg.github.com/penguin-web-services/lovio-api/api:latest
    command: npm run start:prod
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@db:5432/postgres?schema=public
      - JWT_SECRET=${SECRET}
    depends_on:
     - db

  db:
    image: library/postgres:13.1-alpine
    ports:
      - 5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
