name: End to End tests

on:
  pull_request:
    branches:
      - master

defaults:
  run:
    working-directory: app

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD=asdfasdf
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm i
      - name: Run End to End Tests
        run: npm run test
        env:
          DATABASE_URL="postgresql://postgres:asdfasdf@postgres:5432/test?schema=public"
