name: Publish Docker Image

on:
  push:
    branches:
      - master
  release:
    types: [published, prereleased]
  pull_request:
    branches:
      - master

jobs:
  build_dockerfile:
    name: run docker build for Production
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.HUB_USER }}
          password: ${{ secrets.HUB_PASS }}
          repository: penguinws/lovio-api
          tag_with_ref: true
