name: Publish Docker Image

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_dockerfile:
    name: run docker build for Production
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Docker Meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: docker.pkg.github.com/penguin-web-services/lovio-api/api
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: testing
        run: echo ${{ github.repository_owner }}
      - name: testing tags
        run: echo ${{ steps.docker_meta.outputs.tags }}

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          target: production
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
