name: Publish Docker Image

on:
  push:
    branches:
      - master
  release:
    types: [published, prereleased]

jobs:
  build_dockerfile:
    name: run docker build for Production
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: penguin-web-services/lovio-api/api
          tag_with_ref: true
  deploy:
    needs: build_dockerfile
    runs-on: ubuntu-latest
    steps:
      - name: Remote SSH Commands
        uses: appleboy/ssh-action@master
        with:
          script: |
            cd services/lovio-api
            git pull
            docker-compose -f docker-compose.prod.yml pull
            docker-compose -f docker-compose.prod.yml up -d
          host: ${{ secrets.HOST }}
          username: ${{ secrets.username }}
          key: ${{ secrets.PRIVATE_KEY }}
